### PR TITLE
fix(docs): snippets are now replaced in jsdoc comments

### PR DESCRIPTION
**Pull request by bcoe**

### CODE REVIEW

**Comment by tmatsuo** [comment]
I assume that, it is for making generated jsdoc better. Are there any jsdocs for previewing the new result or comparing it with the old jsdoc?

**Comment by bcoe** [comment]
@tmatsuo you can generate locally, I recommend using [nvm](https://github.com/nvm-sh/nvm) to install `node@12`:

```
nvm install 12
```

And then doing the following:

```
git clone git@github.com:googleapis/nodejs-datastore-session.git
cd nodejs-datastore-session
npm i
npm run docs
open docs/index.html
```

I don't believe there will actually be any changes to the datastore documentation, this was specifically to fix a big with some of our libraries like bigquery, which were not replacing `region_tag:`:

https://googleapis.dev/nodejs/bigquery/latest/Dataset.html#Dataset-examples

we keep the file `.jsdoc.js` in a central template, so to address this bug in a percentage of our repositories, we've added it globally.

**Comment by tmatsuo** [comment]
Ok, so I assume that, the `region_tag:` on this page:
https://googleapis.dev/nodejs/bigquery/latest/BigQuery.html

will be fixed with this change. I assume that you have already confirmed this is working for bigquery jsdoc. Am I right?

**Comment by tmatsuo** [comment]
Yeah I confirmed that the current nodejs-bigquery repo generated the jsdoc with replacing the `region_tag:` and such. LGTM

**Pull request merged**
