### PR TITLE
fix(docs): environment variables should be read before defaults

### LINKED ISSUE #150: README examples with environment variables are broken
The examples in the README that involve environment variables are broken.  For example:

      projectId: 'YOUR_PROJECT_ID' || process.env.GCLOUD_PROJECT,

In that example, the environment variable will never be used.  Instead, it should come first:

      projectId: process.env.GCLOUD_PROJECT || 'YOUR_PROJECT_ID',

### PR DESCRIPTION
**Pull request by cashpipeplusplus**
In the original examples:

      projectId: 'YOUR_PROJECT_ID' || process.env.GCLOUD_PROJECT,

The environment variable will never be used.  Instead, it should come first:

      projectId: process.env.GCLOUD_PROJECT || 'YOUR_PROJECT_ID',

Fixes #150

### CODE REVIEW

**Comment by cashpipeplusplus** [comment]
@googlebot I signed it!

**Comment by stephenplusplus** [comment]
This is kind of confusing. I think the code is trying to say, "pass in your project ID, or we'll use the environment variable". It doesn't really look right in code, but if we flip it-- `projectId: process.env.GCLOUD_PROJECT || 'YOUR_PROJECT_ID'`, that isn't actually right in terms of how it works. The project ID provided by the user is honored before the environment variable.

I would say we should just show the user-provided values. That way, the complete example reads:

```js
// For convenience, @google-cloud/datastore automatically looks for the
// GCLOUD_PROJECT environment variable. Or you can explicitly pass in a
// project ID here:
projectId: 'YOUR_PROJECT_ID',

// For convenience, @google-cloud/datastore automatically looks for the
// GOOGLE_APPLICATION_CREDENTIALS environment variable. Or you can
// explicitly pass in that path to your key file here:
keyFilename: '/path/to/keyfile.json',
```

**Comment by stephenplusplus** [comment]
P.S. Thank you for catching this and offering your help to fix it!

**Comment by bcoe** [comment]
@cashpipeplusplus mind making the changes @stephenplusplus recommends, alternatively we could see this over the finish line for you :+1:

**Comment by cashpipeplusplus** [comment]
Sorry, I'm no longer using this module.  Feel free to fix this another way if you like.  Thanks for your attention!

**Pull request closed without merging**
